### PR TITLE
Revised the Connect dialog.

### PR DESCRIPTION
**Pull request by SJLennon**

### CODE REVIEW

**Comment by worksofliam** [comment]
@SJLennon 

Some great changes here. You've actually deleted a file that is referenced in the package.json here: https://github.com/SJLennon/vscode-ibmi-walkthroughs/blob/main/package.json#L36

Is there a plan to recreate that file with different contents? Otherwise it should be removed from the json also.

**Comment by SJLennon** [comment]
Let me look at it this evening.

**Comment by SJLennon** [comment]
Last thing I did was delete compile.png to be tidy.  Fat fingered the selection and deleted compile.png.  Fortunately it was still in my recycle bin.  I believe I have tidied things up.  If not, holler!
@worksofliam

**Comment by worksofliam** [comment]
Looking great @SJLennon!!

Thanks a lot for your work here.

**Pull request merged**
